apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example
  name: zipkin-original
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-app-example
      service: zipkin-original
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: zipkin-original
    spec:
      containers:
      - image: openzipkin/zipkin
        imagePullPolicy: Always
        name: zipkin-original
        ports:
        - containerPort: 9411
          protocol: TCP
        - containerPort: 9410
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
