apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: microservice-app-example
  name: zipkin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-app-example
      service: zipkin
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: microservice-app-example
        service: zipkin
    spec:
      containers:
      - image: openzipkin/zipkin
        imagePullPolicy: Always
        name: zipkin
        ports:
        - containerPort: 9411
          protocol: TCP
        - containerPort: 9410
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
