apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-app-example
  name: zipkin
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    service: zipkin
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
