apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-app-example
  name: zipkin-original
spec:
  ports:
  - port: 9411
    protocol: TCP
    targetPort: 9411
  selector:
    service: zipkin-original
  sessionAffinity: None