apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-app-example
  name: auth-api
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    service: auth-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
