apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice-app-example
  name: users-api
spec:
  ports:
  - port: 8083
    protocol: TCP
    targetPort: 8083
  selector:
    service: users-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
